server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启服务注册中心动态创建路由的功能，利用微服务名创建路由
      routes:
      - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
        #uri: http://localhost:8001   #匹配后提供服务的路由地址,写死的方式
        uri: lb://CLOUD-PROVIDER-PAYMENT-SERVICE #这里使用注册中心的服务名实现带负载均衡的动态路由
        predicates:
        - Path=/payment/get/**   #断言,路径相匹配的进行路由
        - After=2021-04-05T17:20:17.295+08:00[Asia/Shanghai]
        #- Cookie=username,zzyy
        #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为整数的正则表达式

      - id: payment_routh2
        #uri: http://localhost:8001
        uri: lb://CLOUD-PROVIDER-PAYMENT-SERVICE #这里使用注册中心的服务名实现带负载均衡的动态路由
        predicates:
        - Path=/payment/lb/**   #断言,路径相匹配的进行路由
        - After=2021-04-05T17:20:17.295+08:00[Asia/Shanghai]
        #- Cookie=username,zzyy
        #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为整数的正则表达式


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
 
 
