server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.105:8082 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'